### ISSUE TITLE
Debug message: Undefined variable + Function name must be a string

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/edd-recently-viewed-items#1]
Not sure if I'm the only one, but I seem to receive the following error when I'm copying the template files to my own theme's edd_template folder.

Notice: Undefined variable: get_stylesheet_directory in C:\xampp\htdocs\...\plugins\edd-recently-viewed-items-master\includes\misc-functions.php on line 78

Fatal error: Function name must be a string in C:\xampp\htdocs\...\plugins\edd-recently-viewed-items-master\includes\misc-functions.php on line 78

**Comment by mindctrl** [comment]
@kiarashi looks like I have a search/replace operation gone bad. I'll patch that up and see if we can get a quick update out.
