### ISSUE TITLE
Plugin Author/link incorrect

### ISSUE THREAD

**Issue by shaynesanderson** [easydigitaldownloads/edd-recently-viewed-items#11]
## Bug Report

When viewing the main Plugins page, the author and link are incorrect.

Current author: John Parris
Current link: http://www.johnparris.com/wordpress-plugins/edd-recently-viewed-items

![Screenshot_2021-01-27 Plugins ‹ EDD Doc Test — WordPress](https://user-images.githubusercontent.com/1680163/106049303-9c20c700-60ab-11eb-87a6-79561d8fbd30.png)

**Comment by LisaCee** [comment]
PR #12
