### ISSUE TITLE
Template page issue

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/edd-recently-viewed-items#7]
When I copy a template file to my own theme's edd_template folder and 
I add a simple wordpress code like <?php the_excerpt(); ?> 
my Xampp (localhost) Apache crashes and the page no longer loads.
All other pages that doesn't use EDD_RVI works just fine. 
Could this actually be an error inside the plugin? 

Kiarashi

**Comment by mindctrl** [comment]
@kiarashi try this instead:
`echo apply_filters( 'the_excerpt', get_post_field( 'post_content', $item_id ) );`

**Comment by kiarashi** [comment]
Thanks! That code is making it work flawlessy again. :)
